INSERT INTO POSTS (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka je mistryně v odpočívání.', '10-Feb-2021', 1739, 13);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Nemůžu uvěřit, jak je moje kočka chytrá.', '10-Aug-2021', 354, 23);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka ráda sedí na mé klávesnici.', '17-Apr-2024', 535, 6);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka si užívá lenošení na gauči.', '14-Mar-2021', 1385, 23);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Seznamte se s nejlepším přítelem mé kočky – kartonovou krabicí.', '12-Aug-2021', 1095, 19);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka má tu nejjemnější srst.', '19-Jan-2022', 264, 6);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka ráda fotobombí moje fotky.', '02-Nov-2024', 1832, 13);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka ráda sedí na mé klávesnici.', '20-May-2021', 1490, 7);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Nemůžu uvěřit, jak je moje kočka chytrá.', '17-Nov-2022', 1848, 16);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Ocas mé kočky má vlastní rozum.', '06-Dec-2023', 1064, 25);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Myslím, že moje kočka něco plánuje...', '13-Apr-2022', 450, 2);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Právě jsem přistihl svou kočku při nejvtipnější věci!', '20-Feb-2024', 1861, 25);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka dokonale ovládá umění vypadat nevinně.', '06-Oct-2021', 1639, 5);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka je největší jogín.', '10-Dec-2022', 153, 2);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Podívejte se na novou hračku mé kočky!', '28-Nov-2021', 34, 25);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka je mistryně v odpočívání.', '29-Aug-2022', 1227, 21);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Tady je moje kočka, jak mi krade svačinu.', '13-Jul-2024', 802, 7);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka si ráda zdřímne v mé skříni.', '23-Sep-2024', 781, 8);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Seznamte se s nejlepším přítelem mé kočky – kartonovou krabicí.', '01-Mar-2022', 17, 6);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka ráda fotobombí moje fotky.', '30-Jan-2022', 1227, 10);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka vládne obýváku.', '18-Dec-2023', 323, 24);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka vládne obýváku.', '22-Apr-2022', 520, 7);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Podívejte se na novou hračku mé kočky!', '31-Jan-2024', 1343, 24);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka dokonale ovládá umění vypadat nevinně.', '17-Jun-2022', 718, 5);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka je největší jogín.', '27-Dec-2021', 945, 27);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Kdo si taky myslí, že jeho kočka je nejchytřejší?', '25-Jan-2021', 325, 8);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Tady je fotka slavnostní večeře mé kočky.', '01-Jan-2021', 322, 13);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Právě jsem pořídil tuto roztomilou fotku Mourka.', '06-Aug-2021', 893, 15);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka si přivlastnila moje oblíbené křeslo.', '24-Apr-2021', 85, 28);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka si ráda zdřímne v mé skříni.', '05-Jul-2023', 987, 29);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka si myslí, že je lev.', '01-Sep-2023', 1443, 26);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Právě jsem přistihl svou kočku při nejvtipnější věci!', '24-Oct-2021', 481, 4);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka se mnou ráda sleduje televizi.', '11-Apr-2023', 1404, 11);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Přistihl jsem svou kočku, jak si hraje se svým odrazem.', '29-Apr-2024', 113, 10);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Tohle je oblíbené místo mé kočky na spaní.', '15-Sep-2023', 1969, 6);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Kdo si taky myslí, že jeho kočka je nejchytřejší?', '20-Jun-2023', 1963, 11);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka ráda sedí u okna a pozoruje ptáky.', '27-Mar-2022', 1035, 4);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Tady je moje kočka, jak si užívá líné odpoledne.', '12-Apr-2022', 1207, 14);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Podívejte se, jak se moje kočka vyhřívá na slunci!', '23-Mar-2021', 600, 4);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Podívejte se, jak moje kočka reaguje na sníh.', '22-Jul-2021', 489, 28);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka je královna domu.', '01-Jun-2023', 23, 11);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Tohle je oblíbené místo mé kočky na spaní.', '24-Feb-2021', 1315, 4);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka je mistryně v odpočívání.', '21-Jun-2021', 299, 3);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočička se ráda mazlí.', '17-Feb-2022', 959, 13);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka vládne obýváku.', '31-Aug-2024', 1283, 15);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Právě jsem své kočce pořídil nový škrabací strom!', '23-Jan-2021', 1157, 6);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Tohle je oblíbené místo mé kočky na spaní.', '03-Oct-2022', 794, 8);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka ráda sedí u okna a pozoruje ptáky.', '21-Apr-2024', 1988, 9);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Tady je moje kočka, jak předvádí své lovecké dovednosti.', '30-Aug-2024', 168, 26);
INSERT INTO Posts (Text, ShareDate, LikeCount, ID_User) VALUES ('Moje kočka se právě naučila nový trik!', '17-May-2022', 502, 20);